Repository PJX-2024-2/PJX-Client, pull requests merged in 2024-09, with the labels that each got.

#2 [chore] Vite + React + Ts 프로젝트 초기세팅
  .gitignore
  index.html
  package.json
  public/vite.svg
  src/App.tsx
  src/assets/react.svg
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: chore

#10 [chore] lint setting + husky git hooks commit msg 관리
  .eslintrc.cjs
  .gitignore
  .prettierrc
  index.html
  package.json
  public/vite.svg
  src/App.tsx
  src/apis/.gitkeep
  src/assets/fonts/.gitkeep
  src/assets/svg/.gitkeep
  src/components/.gitkeep
  src/context/.gitkeep
  src/hooks/queries/.gitkeep
  src/hooks/useMobile.tsx
  src/layouts/Layout.tsx
  src/main.tsx
  src/pages/.gitkeep
  src/pages/Start/Start.tsx
  src/router/Router.tsx
  src/styles/.gitkeep
  src/types/.gitkeep
  src/utils/.gitkeep
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: chore, 초기세팅

#6 [chore] GlobalStyle 과 mixin 설정
  package.json
  src/main.tsx
  src/styles/.gitkeep
  src/styles/GlobalStyle.ts
  src/styles/index.tsx
  src/styles/mixin.ts
  yarn.lock
Labels: chore, 초기세팅

#14 [chore] theme 생성
  src/assets/fonts/.gitkeep
  src/assets/fonts/Pretendard-Black.woff
  src/assets/fonts/Pretendard-Bold.woff
  src/assets/fonts/Pretendard-ExtraBold.woff
  src/assets/fonts/Pretendard-ExtraLight.woff
  src/assets/fonts/Pretendard-Light.woff
  src/assets/fonts/Pretendard-Medium.woff
  src/assets/fonts/Pretendard-Regular.woff
  src/assets/fonts/Pretendard-SemiBold.woff
  src/assets/fonts/Pretendard-Thin.woff
  src/assets/fonts/pretendard.css
  src/pages/Start/Start.style.ts
  src/pages/Start/Start.tsx
  src/styles/index.tsx
  src/styles/theme.ts
Labels: chore, 초기세팅

#16 Develop에서 main merge (GloblalStyle, theme 반영)
  package.json
  src/assets/fonts/.gitkeep
  src/assets/fonts/Pretendard-Black.woff
  src/assets/fonts/Pretendard-Bold.woff
  src/assets/fonts/Pretendard-ExtraBold.woff
  src/assets/fonts/Pretendard-ExtraLight.woff
  src/assets/fonts/Pretendard-Light.woff
  src/assets/fonts/Pretendard-Medium.woff
  src/assets/fonts/Pretendard-Regular.woff
  src/assets/fonts/Pretendard-SemiBold.woff
  src/assets/fonts/Pretendard-Thin.woff
  src/assets/fonts/pretendard.css
  src/main.tsx
  src/pages/Start/Start.style.ts
  src/pages/Start/Start.tsx
  src/styles/.gitkeep
  src/styles/GlobalStyle.ts
  src/styles/index.tsx
  src/styles/mixin.ts
  src/styles/theme.ts
  yarn.lock
Labels: merge

#21 [초기세팅] color theme 세팅
  src/styles/theme.ts
Labels: feat
