Repository PJX-2024-2/PJX-Client, pull requests merged in 2024-12, with the labels that each got.

#71 [fix] home api 이상한 부분 수정
  src/apis/client.ts
  src/components/BuyCard/BuyCard.tsx
  src/components/CostContent/CostContent.tsx
  src/components/EmotionSelect/EmotionSelect.tsx
  src/components/MonthlyCost/MonthlyCost.tsx
  src/hooks/queries/home/usePostDayPaid.tsx
  src/hooks/queries/home/usePostFeel.tsx
  src/hooks/queries/home/usePostFeelList.tsx
  src/pages/Home/Home.tsx
  src/types/home.ts
Labels: 홈페이지

#73 [지출작성] AI 지출 작성 후 제출 페이지로 파일 객체 넘겨주기
  src/components/WriteCost/AiSubmit/AiSubmit.tsx
  src/components/WriteCost/Submit/CostSubmit.tsx
  src/pages/WriteCost/WriteCost.tsx
  src/types/InputType.ts
Labels: 지출작성페이지

#72 [카카오 공유하기] 카카오톡 공유하기 기능
  index.html
  src/assets/image/logo.png
  src/assets/svg/IcShare.tsx
  src/components/GNB/GNB.style.ts
  src/components/GNB/GNB.tsx
  src/components/LoginCallback/LoginCallback.tsx
  src/components/OnboardingSteps/Step2/Step2.tsx
  src/pages/Mypage/Mypage.tsx
  src/pages/Start/Start.tsx
  src/utils/shareKakao.ts
Labels: feat, 홈페이지

#79 [refactor] 2차 QA (로그인 플로우 수정, 로딩 처리, 마이페이지 지출 분석 수정)
  package.json
  src/assets/lottie/loadingLottie.json
  src/components/LoginCallback/LoginCallback.tsx
  src/components/WriteCost/AiSubmit/AiSubmit.style.ts
  src/components/WriteCost/AiSubmit/AiSubmit.tsx
  src/components/WriteCost/CostPrice/CostPrice.tsx
  src/components/WriteCost/Submit/CostSubmit.tsx
  src/components/common/Title/Title.style.ts
  src/hooks/queries/onboarding/useGetNickname.tsx
  src/hooks/queries/onboarding/usePostNickname.tsx
  src/pages/Loading/Loading.style.ts
  src/pages/Loading/Loading.tsx
  src/pages/Mypage/Mypage.style.ts
  src/pages/Mypage/Mypage.tsx
  src/pages/Start/Start.tsx
  src/pages/WriteType/WriteType.style.ts
  src/pages/WriteType/WriteType.tsx
  yarn.lock
Labels: refactor
