Repository PJX-2024-2/PJX-Client, pull requests merged in 2024-10, with the labels that each got.

#17 [feat] 시작 페이지 뷰 퍼블리싱
  src/assets/svg/IcKakaoButton.tsx
  src/assets/svg/IcTitleIcon.tsx
  src/assets/svg/index.ts
  src/components/common/.gitkeep
  src/components/common/Button/KakaoLoginButton/BtnKakaoLogin.style.ts
  src/components/common/Button/KakaoLoginButton/BtnKakaoLogin.tsx
  src/components/common/Button/LargeButton/BtnLarge.style.ts
  src/components/common/Button/LargeButton/BtnLarge.tsx
  src/components/common/Button/SmallButton/BtnSmall.style.ts
  src/components/common/Button/SmallButton/BtnSmall.tsx
  src/pages/Start/Start.style.ts
  src/pages/Start/Start.tsx
  src/styles/theme.ts
Labels: feat, 시작페이지

#23 [온보딩] 온보딩 1차 뷰 구현
  src/assets/profileMockImage.png
  src/assets/svg/IcCheck.tsx
  src/assets/svg/IcKakaoButton.tsx
  src/assets/svg/IcPlus.tsx
  src/assets/svg/IcTitleIcon.tsx
  src/assets/svg/index.ts
  src/components/.gitkeep
  src/components/Friend/FriendItem/FriendItem.style.ts
  src/components/Friend/FriendItem/FriendItem.tsx
  src/components/Friend/FriendList/FriendList.style.ts
  src/components/Friend/FriendList/FriendList.tsx
  src/components/OnboardingSteps/OnboardingInput/OnboardingInput.style.ts
  src/components/OnboardingSteps/OnboardingInput/OnboardingInput.tsx
  src/components/OnboardingSteps/OnboardingTitle/OnboardingTitle.style.ts
  src/components/OnboardingSteps/OnboardingTitle/OnboardingTitle.tsx
  src/components/OnboardingSteps/Step1/Step1.style.ts
  src/components/OnboardingSteps/Step1/Step1.tsx
  src/components/OnboardingSteps/Step2/Step2.style.ts
  src/components/OnboardingSteps/Step2/Step2.tsx
  src/components/OnboardingSteps/Step3/Step3.style.ts
  src/components/OnboardingSteps/Step3/Step3.tsx
  src/components/common/.gitkeep
  src/components/common/Button/LargeButton/BtnLarge.style.ts
  src/components/common/Button/SmallButton/BtnSmall.style.ts
  src/components/common/Dropbox/Dropbox.style.ts
  src/components/common/Dropbox/Dropbox.tsx
  src/hooks/common/useFunnel.tsx
  src/pages/.gitkeep
  src/pages/Onboarding/Onboarding.style.ts
  src/pages/Onboarding/Onboarding.tsx
  src/router/Router.tsx
  src/styles/theme.ts
  src/types/StepPropsType.ts
  src/utils/.gitkeep
  src/utils/emailDomains.ts
Labels: feat, 온보딩

#25 Develop에서 main merge (day picker 오류 해결)
  src/components/Calendar/Calendar.tsx
Labels: bug

#30 [검색페이지] 검색페이지 뷰 생성
  src/assets/svg/IcBack.tsx
  src/assets/svg/index.ts
  src/components/Friend/FriendItem/FriendItem.style.ts
  src/components/Friend/FriendItem/FriendItem.tsx
  src/components/Search/Search.style.ts
  src/components/Search/Search.tsx
  src/components/Search/SearchNone/SearchNone.style.ts
  src/components/Search/SearchNone/SearchNone.tsx
  src/components/Search/SearchPerson/SearchPerson.style.ts
  src/components/Search/SearchPerson/SearchPerson.tsx
  src/components/Search/SearchingBar/SearchingBar.style.ts
  src/components/Search/SearchingBar/SearchingBar.tsx
  src/pages/Feed/Feed.style.ts
  src/pages/Feed/Feed.tsx
Labels: feat, 검색페이지

#33 [마이페이지] 마이페이지 뷰 제작
  src/assets/svg/IcBack.tsx
  src/assets/svg/IcCheck.tsx
  src/assets/svg/IcPen.tsx
  src/assets/svg/IcRight.tsx
  src/assets/svg/index.ts
  src/components/EditProfile/EditProfile.style.ts
  src/components/EditProfile/EditProfile.tsx
  src/components/Friend/FriendItem/FriendItem.tsx
  src/components/MonthlyCost/MonthlyCost.tsx
  src/components/OnboardingSteps/OnboardingTitle/OnboardingTitle.style.ts
  src/components/OnboardingSteps/OnboardingTitle/OnboardingTitle.tsx
  src/components/OnboardingSteps/Step1/Step1.tsx
  src/components/OnboardingSteps/Step2/Step2.tsx
  src/components/OnboardingSteps/Step3/Step3.tsx
  src/components/common/Title/Title.style.ts
  src/components/common/Title/Title.tsx
  src/pages/Mypage/Mypage.style.ts
  src/pages/Mypage/Mypage.tsx
  src/pages/Mypage/MypageFriends/MypageFriends.style.ts
  src/pages/Mypage/MypageFriends/MypageFriends.tsx
  src/pages/Mypage/Profile/Profile.style.ts
  src/pages/Mypage/Profile/Profile.tsx
  src/router/Router.tsx
  src/styles/theme.ts
Labels: feat, 마이페이지

#39 [공통 컴포넌트] 감정 선택 모달 및 친구 추가 버튼 로직
  src/assets/svg/IcPlus.tsx
  src/components/BuyCard/BuyCard.style.ts
  src/components/EmotionSelect/EmotionSelect.style.ts
  src/components/EmotionSelect/EmotionSelect.tsx
  src/components/common/Button/Rounded/Default/Default.style.ts
  src/components/common/Button/Rounded/Default/Default.tsx
  src/components/common/Button/Rounded/Primary/Primary.style.ts
  src/components/common/Button/Rounded/Primary/Primary.tsx
  src/pages/Feed/Feed.style.ts
  src/pages/Home/Home.style.ts
  src/pages/Home/Home.tsx
Labels: feat

#36 [알림 페이지] 알림 페이지 뷰 구현
  src/assets/svg/IcAngry.tsx
  src/assets/svg/IcHappy.tsx
  src/assets/svg/IcNone.tsx
  src/assets/svg/IcPick.tsx
  src/assets/svg/IcPlusRound.tsx
  src/assets/svg/IcSad.tsx
  src/assets/svg/IcSuprised.tsx
  src/assets/svg/IcThinking.tsx
  src/assets/svg/index.ts
  src/components/Alarm/AlarmItem/AlarmItem.style.ts
  src/components/Alarm/AlarmItem/AlarmItem.tsx
  src/components/Alarm/AlarmList/AlarmList.style.ts
  src/components/Alarm/AlarmList/AlarmList.tsx
  src/components/common/Button/RoundedButton/BtnRounded.style.ts
  src/components/common/Button/RoundedButton/BtnRounded.tsx
  src/components/common/None/None.style.ts
  src/components/common/None/None.tsx
  src/pages/Alarm/Alarm.style.ts
  src/pages/Alarm/Alarm.tsx
  src/styles/theme.ts
Labels: feat, 알림페이지

#44 [api] apiInstance 생성
  package.json
  src/apis/.gitkeep
  src/apis/apiInstance.ts
  yarn.lock
Labels: feat

#45 [api 연결] ai 영수증 이미지 분석 결과
  package.json
  src/App.tsx
  src/apis/apiInstance.ts
  src/hooks/queries/receipt/usePostReceiptAnalyze.tsx
  src/types/.gitkeep
  src/types/receipt.ts
  yarn.lock
Labels: feat

#46 [feat] 지출 입력 컴포넌트 뷰 구현
  src/assets/svg/IcWriteAi.tsx
  src/assets/svg/IcWriteSelf.tsx
  src/assets/svg/index.ts
  src/components/WriteCost/AiSubmit/AiSubmit.style.ts
  src/components/WriteCost/AiSubmit/AiSubmit.tsx
  src/components/WriteCost/CostName/CostName.style.ts
  src/components/WriteCost/CostName/CostName.tsx
  src/components/WriteCost/CostPrice/CostPrice.style.ts
  src/components/WriteCost/CostPrice/CostPrice.tsx
  src/components/WriteCost/Submit/CostSubmit.style.ts
  src/components/WriteCost/Submit/CostSubmit.tsx
  src/components/common/Button/ContainedButton/BtnContained.style.ts
  src/components/common/Button/ContainedButton/BtnContained.tsx
  src/components/common/WriteHeader/WriteHeader.style.ts
  src/components/common/WriteHeader/WriteHeader.tsx
  src/pages/WriteCost/WriteCost.style.ts
  src/pages/WriteCost/WriteCost.tsx
  src/pages/WriteType/WriteType.style.ts
  src/pages/WriteType/WriteType.tsx
  src/router/Router.tsx
  src/types/InputType.ts
Labels: feat, 지출작성페이지
