Repository PJX-2024-2/PJX-Client, pull requests merged in 2024-11, with the labels that each got.

#53 [fix] 카카오 토큰과 jwt 토큰 구분
  src/components/LoginCallback/LoginCallback.tsx
  src/hooks/queries/login/usePostAccessCode.tsx
Labels: feat

#55 [feat] UserContext 적용
  src/App.tsx
  src/components/LoginCallback/LoginCallback.tsx
  src/context/User/UserInfoContext.tsx
  src/pages/Mypage/Mypage.tsx
  src/types/userInfo.ts
Labels: feat

#57 refactor: 시작페이지 아이콘 및 텍스트 변동
  src/assets/svg/IcTitleIcon.tsx
  src/pages/Start/Start.style.ts
  src/pages/Start/Start.tsx
Labels: style

#58 [feat] 온보딩 닉네임 중복 api 연결
  src/App.tsx
  src/components/OnboardingSteps/OnboardingInput/OnboardingInput.style.ts
  src/components/OnboardingSteps/OnboardingInput/OnboardingInput.tsx
  src/components/OnboardingSteps/Step2/Step2.tsx
  src/hooks/common/useFunnel.tsx
  src/hooks/queries/onboarding/useGetNickname.tsx
  src/hooks/queries/onboarding/usePostNickname.tsx
  src/pages/Mypage/Mypage.tsx
  src/pages/Onboarding/Onboarding.tsx
  src/pages/Start/Start.tsx
Labels: feat, 온보딩

#64 [feat] 카카오 로그인 uri 수정
  src/components/LoginCallback/LoginCallback.tsx
  src/hooks/queries/login/usePostAccessCode.tsx
Labels: feat

#62 [feat] home api 더미데이터 + 뷰 마무리
  src/components/CostContent/CostContent.style.ts
  src/components/CostContent/CostContent.tsx
  src/components/EmotionSelect/EmotionSelect.style.ts
  src/components/EmotionSelect/EmotionSelect.tsx
  src/components/GNB/GNB.style.ts
  src/components/GNB/GNB.tsx
  src/components/MonthlyCost/MonthlyCost.tsx
  src/components/PaidContent/PaidContent.style.ts
  src/components/PaidContent/PaidContent.tsx
  src/components/SetMonthGoal/SetMonthGoal.style.ts
  src/components/SetMonthGoal/SetMonthGoal.tsx
  src/hooks/queries/home/usePostDayPaid.tsx
  src/hooks/queries/home/usePostFeel.tsx
  src/hooks/queries/home/usePostFeelList.tsx
  src/hooks/queries/home/usePostMonthGoal.tsx
  src/hooks/queries/home/usePostPaid.tsx
  src/pages/Home/Home.tsx
  src/router/Router.tsx
  src/types/home.ts
Labels: feat
